# Generated by Django 3.0 on 2023-12-14 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0002_auto_20231214_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=1.0), django.core.validators.MaxValueValidator(limit_value=10.0)]),
        ),
    ]
