# Generated by Django 3.0 on 2023-12-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0003_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='homework_app.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(related_name='starring', through='homework_app.PersonMovie', to='homework_app.Person'),
        ),
    ]
